name: CI Workflow

on:
  push:
    branches:
      - work-branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ libgtest-dev -y

      - name: Build the project
        run: make test

      - name: Run tests
        run: ./test

